### ISSUE TITLE
sbt can't work out the minor version of 2.11.8-tl-201604131941

### ISSUE THREAD

**Issue by fommil** [milessabin/si2712fix-demo#7]
sbt looks at 2.11.8 and understands that "_2.11" should be appended to artefact names

but when it sees "2.11.8-tl-201604131941" it thinks "2.11.8-tl-201604131941" should be appended.

You might want to add

```
scalaBinaryVersion := CrossVersion.binaryScalaVersion("2.11")
```

to your `build.sbt` so that people can just copy and paste the necessary boilerplate.

**Comment by milessabin** [comment]
Fixed in f0283f247180536211b607fd5fc4f3a5ff92bb29.
