### ISSUE TITLE
please publish sources / javadocs for your build of scala

### ISSUE THREAD

**Issue by fommil** [milessabin/si2712fix-demo#8]
the ensime tests assume that the sources / javadocs of scala-library are available, but you didn't publish them, so I can't get a green light on SI-2712 regression testing :sob: https://github.com/ensime/ensime-server/pull/1419

**Comment by milessabin** [comment]
I did publish them ... they're in the repo [here](http://milessabin.com/scalatl/org/scala-lang/scala-library/2.11.8-tl-201604151108/). Is there something else you need?

**Comment by fommil** [comment]
Hmm, sbt is not able to find them. I'll have another look.

**Comment by fommil** [comment]
oh, very interesting. I think sbt might need something extra to search your repository when resolving scala's classifiers.

**Comment by fommil** [comment]
I worked out what it is. When defining the `resolvers` it has to go in the `override val settings =` bit, not in a `commonSettings`. Not your bug.
